```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, include=FALSE}
library(RColorBrewer)
library(lattice)
library(tidyverse)
library(here)
library(tictoc)

library(ggplot2)
library(ggpubr)
library(sf)
library(terra)

library(tmap)
library(tmaptools)
library(RColorBrewer)
library(viridis)

terraOptions(memfrac=0.8, tempdir = here("Scratch"), progress=10)
```
#Introduction
In this script, I use the sampled points csvs to extract the time series from the stl files on the server. 
(1) Function to use to extract time series (monthly) of sampled points in NDVI and EVI stl files on server
Note that the function below was run on the server and the resulting files were accordingly moved from server

#Step 1- function 
```{r}
step2<- function (sample_df, stl_df){
  cell_sample<- unique(sample_df$cell) #"cell" is "NDVI_ID" or the "ID" of EVI and/or anisoEVI
  x<- stl_df %>% filter(cell %in% cell_sample)
}

#sample_df is the csv files in Outputs> TrajectoryPlotting
#stl_df is the 3 compiled files in the STL Decomposition folder of each index for swin=11
```