```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, include=FALSE}
library(RColorBrewer)
library(lattice)
library(tidyverse)
library(here)
library(tictoc)

library(ggplot2)
library(ggpubr)
library(sf)
library(terra)

library(tmap)
library(tmaptools)
library(RColorBrewer)
library(viridis)

terraOptions(memfrac=0.8, tempdir = here("Scratch"), progress=10)
```

##Introduction 
In this script I calculate the fractional area of savanna, forest and grass formation according
to Mapbiomas through time and look at anomalies/trends. 
(1) Crop /mask data from gee - https://code.earthengine.google.com/?scriptPath=users%2Ftrishagopalakrishna%2Fdefault%3AAbruptChanges_Cerrado%2FDrivers%2Fmapbiomas_Formations
(2) Anomalies/trend through time

#Step 1- reading data processed in gee, crop/mask and animation map 
```{r}
#Data input
raster_filepath <- list.files(path = here("Data", "Mapbiomas_formations"), pattern= ".tif$", all.files=TRUE, full.names=TRUE)
raster_list<-lapply(raster_filepath, rast)

d_trans<- st_read(here ("Data", "Cattelanetal_Clustering", "cerrado_climate_zones.shp"))
d_trans<- st_transform(d_trans, crs = 4326)
cerrado<- d_trans %>% st_union()

#Crop/mask
crop_mask_function <- function (raster){
  x_crop <- terra::crop(raster, vect(cerrado))
  x_mask <- terra::mask (x_crop, vect(cerrado))
  x_mask
}

Sys.time(); forest_percentage <- crop_mask_function(raster_list[[1]]); Sys.time()
Sys.time(); grass_percentage <- crop_mask_function(raster_list[[2]]); Sys.time()
Sys.time(); savanna_percentage <- crop_mask_function(raster_list[[3]]); Sys.time()


#Time period 2002 - 2021 
forest_percentage<- forest_percentage[[18:37]]
writeRaster(forest_percentage, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "forest_percentage_5km_2002_2021.tif"))
grass_percentage<- grass_percentage[[18:37]]
writeRaster(grass_percentage, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "grass_percentage_5km_2002_2021.tif"))
savanna_percentage<- savanna_percentage[[18:37]]
writeRaster(savanna_percentage, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "savanna_percentage_5km_2002_2021.tif"))

#Map
animation_map_function <- function (timeseries_raster){
  animation_x_time_map<-
   tm_shape(cerrado)+ tm_borders()+
   tm_shape (timeseries_raster)+
   tm_raster(col.scale = tm_scale_intervals(n=5, style= "quantile", values = "Greens")) +
   tm_facets(nrow=1, ncol=1, free.coords = TRUE) 
  animation_x_time_map
}

map_forest<- animation_map_function(forest_percentage)
tmap_animation(map_forest, filename = here("Outputs", "OtherVariables", "Formations_Heterogeniety", "annual_forestformationpercentage_2002_2021.gif"),
                delay = 50, loop = TRUE, restart.delay = 500,
                width = 900, height = 900, dpi = 150)
map_grass<- animation_map_function(grass_percentage)
tmap_animation(map_grass, filename = here("Outputs", "OtherVariables", "Formations_Heterogeniety", "annual_grassformationpercentage_2002_2021.gif"),
                delay = 50, loop = TRUE, restart.delay = 500,
                width = 900, height = 900, dpi = 150)
map_savanna<- animation_map_function(savanna_percentage)
tmap_animation(map_savanna, filename = here("Outputs", "OtherVariables", "Formations_Heterogeniety", "annual_savannaformationpercentage_2002_2021.gif"),
                delay = 50, loop = TRUE, restart.delay = 500,
                width = 900, height = 900, dpi = 150)
remove(crop_mask_function, raster_filepath, raster_list)
remove(animation_map_function, map_forest, map_grass, map_savanna)

```

#Step 2 - anomalies/trend calculation
```{r}
forest_percentage<- rast(here("Outputs", "OtherVariables", "Formations_Heterogeniety", "forest_percentage_5km_2002_2021.tif"))
grass_percentage<- rast(here("Outputs", "OtherVariables", "Formations_Heterogeniety", "grass_percentage_5km_2002_2021.tif"))
savanna_percentage<- rast(here("Outputs", "OtherVariables", "Formations_Heterogeniety", "savanna_percentage_5km_2002_2021.tif"))

#1- std deviation
Sys.time(); std_forest <- terra::app (forest_percentage, fun = sd); Sys.time()
Sys.time(); std_grass <- terra::app (grass_percentage, fun = sd); Sys.time()
Sys.time(); std_savanna <- terra::app (savanna_percentage, fun = sd); Sys.time()

#2- linear regression through time
lm_function <- function (x){
  Y<- 1:length(x)
  
  if(all(is.na(x))){
    return (NA)
  } else{
    lm_model<- lm(x ~ Y )
    slope_coefficient<- lm_model$coefficients[2]
    slope_coefficient
  }
}
Sys.time(); lm_slope_forest <- terra::app (forest_percentage, fun = lm_function); Sys.time()
Sys.time(); lm_slope_grass <- terra::app (grass_percentage, fun = lm_function); Sys.time()
Sys.time(); lm_slope_savanna <- terra::app (savanna_percentage, fun = lm_function); Sys.time()

#3- mann kendal correlation through time
#install.packages("Kendall")
library(Kendall)
MKtau <- function(z){
  if(all(is.na(z))){
    return (NA)
  } else{
    as.numeric(Kendall::MannKendall(z)$tau)
  }
} 
Sys.time(); kendall_tau_forest <- terra::app (forest_percentage, fun = MKtau); Sys.time()
Sys.time(); kendall_tau_grass <- terra::app (grass_percentage, fun = MKtau); Sys.time()
Sys.time(); kendall_tau_savannna <- terra::app (savanna_percentage, fun = MKtau); Sys.time()

#4- theilsen regression
library(mblm)
theilsen_function <- function(z){
  Y<- 1:length(z)
  
  if(all(is.na(z))){
    return (NA)
  } else{
    theilsen_model<- mblm::mblm(z ~ Y, repeated = FALSE)
    slope_coefficient <- theilsen_model$coefficients[2]
    slope_coefficient
  }
} 
Sys.time(); theilsen_forest <- terra::app (forest_percentage, fun = theilsen_function); Sys.time()
#writeRaster(theilsen_forest, here("Outputs","OtherVariables", "Formations_Heterogeniety", "theilsen_forestpercentage.tif"))
Sys.time(); theilsen_grass <- terra::app (grass_percentage, fun = theilsen_function); Sys.time()
#writeRaster(theilsen_grass, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "theilsen_grasspercentage.tif"))
Sys.time(); theilsen_savanna <- terra::app (savanna_percentage, fun = theilsen_function); Sys.time()
#writeRaster(theilsen_savanna, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "theilsen_savannapercentage.tif"))


#Map making
d_trans<- st_read(here ("Data", "Cattelanetal_Clustering", "cerrado_climate_zones.shp"))
d_trans<- st_transform(d_trans, crs = 4326)
d_trans<- d_trans %>% mutate(area_km= terra::expanse(vect(d_trans), unit="km"))
cerrado<- d_trans %>% st_union()

mapping_function <- function (anomoly_raster, title){
  x_map<- tm_shape(cerrado)+ tm_borders()+
    tm_shape (anomoly_raster) + 
    tm_raster(col.scale = tm_scale_intervals(values = "Reds"),
              col.legend = tm_legend(title = title)) +
    tm_layout(legend.text.size = 1, title.size = 4) 
  x_map
}
Sys.time();std_forest <- mapping_function (std_forest, "Std"); Sys.time()
Sys.time();lm_forest <- mapping_function (lm_slope_forest, "Linear Regression"); Sys.time()
Sys.time();tau_forest <- mapping_function (kendall_tau_forest, "Mann-Kendall"); Sys.time()
Sys.time();theilsen_forest <- mapping_function (theilsen_forest, "Theil-Sen Regression"); Sys.time()

anomoly_results_forest<- tmap_arrange(std_forest, lm_forest, tau_forest, theilsen_forest, ncol = 4, nrow= 1) 
tmap_save(anomoly_results_forest, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "anomoly_forestpercentage_methods_results.png"),
        height = 50, width = 50, units = "cm", dpi=700)

Sys.time();std_grass <- mapping_function (std_grass, "Std"); Sys.time()
Sys.time();lm_grass <- mapping_function (lm_slope_grass, "Linear Regression"); Sys.time()
Sys.time();tau_grass <- mapping_function (kendall_tau_grass, "Mann-Kendall"); Sys.time()
Sys.time();theilsen_grass <- mapping_function (theilsen_grass, "Theil-Sen Regression"); Sys.time()

anomoly_results_grass<- tmap_arrange(std_grass, lm_grass, tau_grass, theilsen_grass, ncol = 4, nrow= 1) 
tmap_save(anomoly_results_grass, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "anomoly_grasspercentage_methods_results.png"),
        height = 50, width = 50, units = "cm", dpi=700)

Sys.time();std_savanna <- mapping_function (std_savanna, "Std"); Sys.time()
Sys.time();lm_savanna <- mapping_function (lm_slope_savanna, "Linear Regression"); Sys.time()
Sys.time();tau_savanna <- mapping_function (kendall_tau_savannna, "Mann-Kendall"); Sys.time()
Sys.time();theilsen_savanna <- mapping_function (theilsen_savanna, "Theil-Sen Regression"); Sys.time()

anomoly_results_savanna<- tmap_arrange(std_savanna, lm_savanna, tau_savanna, theilsen_savanna, ncol = 4, nrow= 1) 
tmap_save(anomoly_results_savanna, here("Outputs", "OtherVariables", "Formations_Heterogeniety", "anomoly_savannapercentage_methods_results.png"),
        height = 50, width = 50, units = "cm", dpi=700)

```



