```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, include=FALSE}
library(RColorBrewer)
library(lattice)
library(tidyverse)
library(here)
library(tictoc)

library(ggplot2)
library(ggpubr)
library(sf)
library(terra)

library(tmap)
library(tmaptools)
library(RColorBrewer)
library(viridis)

terraOptions(memfrac=0.8, tempdir = here("Scratch"), progress=10)
```
##Introduction
In this script, I extract prepare time series of anisoEVI, kNDVI, NDVI & EVI by doing EDA
in known area. I then extract the indices in the  study area delineated in 1_studyarea_delineation.Rmd

#1. Preparation of anisoEVI, kNDVI, NDVI
<<<<<<<<Do not run this chunk as products have been written out>>>>>>
```{r}
#1. anisoEVI
#evi_list <- list.files(path = here("Data", "Indices", "AnisoEVI_Cerrado_GEE"), pattern='.tif$', all.files=TRUE, full.names=TRUE)
#evi_raster_list<-lapply(evi_list, rast)
#tic(); evi<- do.call(mosaic,evi_raster_list); toc() #4.2 hours
#writeRaster(evi, here("Data", "Indices", "AnisoEVI_Cerrado_GEE", "mosaiced_anisoEVI.tif"))

evi<- rast(here("Data", "Indices", "AnisoEVI_Cerrado_GEE", "mosaiced_anisoEVI.tif"))
tic();evi<- evi/10^4;toc() #scaling factor mentioned on the description page of the GEE asset

##changing band names to year and months
colnames<- list()
tic(); for ( i in 1:nlyr(evi)){
  x<- names(evi)[[i]]
  y<- paste0(strsplit(x, "_")[[1]][5], "_",strsplit(x, "_")[[1]][6] )
  colnames[[i]] <-y
}; toc()
colnames<- unlist(colnames)
names(evi)<- colnames
remove(i,x,y, colnames)

#2.kNDVI
#kndvi_list <- list.files(path = here("Data", "Indices", "kNDVI_Cerrado_GEE"), pattern='.tif$', all.files=TRUE, full.names=TRUE)
#kndvi_raster_list<-lapply(kndvi_list, rast)
#tic(); kndvi<- rast(kndvi_raster_list); toc() 
#writeRaster(kndvi, here("Data", "Indices", "AnisoEVI_Cerrado_GEE", "kndvi_stack.tif"))
#remove(kndvi_raster_list, kndvi_list)

kndvi<- rast(here("Data", "Indices", "AnisoEVI_Cerrado_GEE", "kndvi_stack.tif"))
colnames<- list()
tic(); for ( i in 1:nlyr(kndvi)){
  x<- names(kndvi)[[i]]
  y<- paste0(strsplit(x, "_")[[1]][2], "_",strsplit(x, "_")[[1]][3] )
  colnames[[i]] <-y
}; toc()
colnames<- unlist(colnames)
names(kndvi)<- colnames
remove(i,x,y, colnames)

kndvi<- kndvi[[1:262]] #excluding year 2022

#3.NDVI
#ndvi_list <- list.files(path = here("Data", "Indices", "Cerrado_monthlyNDVI_GEE"), pattern='.tif$', all.files=TRUE, full.names=TRUE)
#ndvi_raster_list<-lapply(ndvi_list, rast)
#tic(); ndvi<- do.call(mosaic, ndvi_raster_list); toc() #2 hours
#Sys.time(); writeRaster(ndvi, here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "mosaiced_ndvi.tif")); Sys.time()
#remove(ndvi_list, ndvi_raster_list)

ndvi<- rast(here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "mosaiced_ndvi.tif"))
colnames<- list()
tic(); for ( i in 1:nlyr(ndvi)){
  x<- names(ndvi)[[i]]
  y<- paste0(strsplit(x, "_")[[1]][1], "_",strsplit(x, "_")[[1]][2] )
  colnames[[i]] <-y
}; toc()
colnames<- unlist(colnames)
#names(ndvi)<- colnames
#remove(i,x,y, colnames)

#ndvi<- ndvi[[2:263]]

#Sys.time(); ndvi_proj<- terra::project(ndvi, kndvi, method= "bilinear", align= T); Sys.time()
#Sys.time(); ndvi_proj<- terra::crop(ndvi_proj, d_trans); Sys.time()
#Sys.time(); writeRaster(ndvi_proj, here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "mosaiced_ndvi_proj_2000Maronwards.tif")); Sys.time()
#ndvi_proj<- rast(here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "mosaiced_ndvi_proj_2000Maronwards.tif")); Sys.time()
#ndvi_proj_scale<- ndvi_proj * 0.0001
#Sys.time(); writeRaster(ndvi_proj_scale, here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "mosaiced_ndvi_proj_scaled_2000Maronwards.tif")); Sys.time()
#remove(ndvi_proj)
#remove(ndvi_list, ndvi_raster_list)

ndvi_proj_scale<- rast(here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "mosaiced_ndvi_proj_scaled_2000Maronwards.tif")); Sys.time()
#rerun lines 77-84
colnames<- colnames[2:263]
names(ndvi_proj_scale)<- colnames
remove(i,x,y, colnames)
remove(ndvi)

#4. Crop/mask to Cerrado 
d_trans<- st_read(here ("Data", "Cattelanetal_Clustering", "cerrado_climate_zones.shp"))
d_trans<- st_transform(d_trans, crs = 4326)
cerrado<- d_trans %>% st_union()

Sys.time();evi_crop_central<- terra::crop(evi, vect(d_trans$geometry[[1]]))
evi_mask_central<- terra::mask(evi_crop_central, vect(d_trans$geometry[[1]])); Sys.time()
Sys.time(); evi_crop_southern<- terra::crop(evi, vect(d_trans$geometry[[2]]))
evi_mask_southern<- terra::mask(evi_crop_southern, vect(d_trans$geometry[[2]])); Sys.time()
Sys.time(); evi_crop_eastern<- terra::crop(evi, vect(d_trans$geometry[[3]]))
evi_mask_eastern<- terra::mask(evi_crop_eastern, vect(d_trans$geometry[[3]])); Sys.time()
remove(evi_crop_central, evi_crop_southern, evi_crop_eastern)
writeRaster(evi_mask_central, here("Data", "Indices", "AnisoEVI_Cerrado_GEE", "Zone_EVI", "anisoEVI_central.tif"))
writeRaster(evi_mask_southern, here("Data", "Indices", "AnisoEVI_Cerrado_GEE","Zone_EVI", "anisoEVI_southern.tif"))
writeRaster(evi_mask_eastern, here("Data", "Indices", "AnisoEVI_Cerrado_GEE","Zone_EVI", "anisoEVI_eastern.tif"))
remove(evi_mask_central, evi_mask_eastern, evi_mask_southern)

Sys.time();kndvi_crop_central<- terra::crop(kndvi, vect(d_trans$geometry[[1]]))
kndvi_mask_central<- terra::mask(kndvi_crop_central, vect(d_trans$geometry[[1]])); Sys.time()
Sys.time(); kndvi_crop_southern<- terra::crop(kndvi, vect(d_trans$geometry[[2]]))
kndvi_mask_southern<- terra::mask(kndvi_crop_southern, vect(d_trans$geometry[[2]])); Sys.time()
Sys.time(); kndvi_crop_eastern<- terra::crop(kndvi, vect(d_trans$geometry[[3]]))
kndvi_mask_eastern<- terra::mask(kndvi_crop_eastern, vect(d_trans$geometry[[3]])); Sys.time()
remove(kndvi_crop_central, kndvi_crop_southern, kndvi_crop_eastern)
writeRaster(kndvi_mask_central, here("Data", "Indices", "kNDVI_Cerrado_GEE", "Zone_kndvi", "kndvi_central.tif"))
writeRaster(kndvi_mask_southern, here("Data", "Indices", "kNDVI_Cerrado_GEE","Zone_kndvi", "kndvi_southern.tif"))
writeRaster(kndvi_mask_eastern, here("Data", "Indices", "kNDVI_Cerrado_GEE","Zone_kndvi", "kndvi_eastern.tif"))
remove(kndvi_mask_central, kndvi_mask_eastern, kndvi_mask_southern)

Sys.time();ndvi_crop_central<- terra::crop(ndvi_proj_scale, vect(d_trans$geometry[[1]]))
ndvi_mask_central<- terra::mask(ndvi_crop_central, vect(d_trans$geometry[[1]])); Sys.time()
Sys.time(); ndvi_crop_southern<- terra::crop(ndvi_proj_scale, vect(d_trans$geometry[[2]]))
ndvi_mask_southern<- terra::mask(ndvi_crop_southern, vect(d_trans$geometry[[2]])); Sys.time()
Sys.time(); ndvi_crop_eastern<- terra::crop(ndvi_proj_scale, vect(d_trans$geometry[[3]]))
ndvi_mask_eastern<- terra::mask(ndvi_crop_eastern, vect(d_trans$geometry[[3]])); Sys.time()
remove(ndvi_crop_central, ndvi_crop_southern, ndvi_crop_eastern)
writeRaster(ndvi_mask_central, here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "Zone_ndvi", "ndvi_central.tif"))
writeRaster(ndvi_mask_southern, here("Data", "Indices", "Cerrado_monthlyNDVI_GEE","Zone_ndvi", "ndvi_southern.tif"))
writeRaster(ndvi_mask_eastern, here("Data", "Indices", "Cerrado_monthlyNDVI_GEE","Zone_ndvi", "ndvi_eastern.tif"))
remove(ndvi_mask_central, ndvi_mask_eastern, ndvi_mask_southern)
remove(kndvi, evi, ndvi_proj_scale)

```

#2. Basic EDA of anisoEVI, kNDVI, NDVI
```{r}
#central 
evi_mask_central<- rast(here("Data", "Indices", "AnisoEVI_Cerrado_GEE", "Zone_EVI", "anisoEVI_central.tif"))
kndvi_mask_central<- rast(here("Data", "Indices", "kNDVI_Cerrado_GEE", "Zone_kndvi", "kndvi_central.tif"))
ndvi_mask_central<- rast(here("Data", "Indices", "Cerrado_monthlyNDVI_GEE", "Zone_ndvi", "ndvi_central.tif"))

#southern
evi_mask_southern<- rast(here("Data", "Indices", "AnisoEVI_Cerrado_GEE","Zone_EVI", "anisoEVI_southern.tif"))
kndvi_mask_southern<- rast(here("Data", "Indices", "kNDVI_Cerrado_GEE","Zone_kndvi", "kndvi_southern.tif"))
ndvi_mask_southern<- rast(here("Data", "Indices", "Cerrado_monthlyNDVI_GEE","Zone_ndvi", "ndvi_southern.tif"))

#eastern
evi_mask_eastern<- rast(here("Data", "Indices", "AnisoEVI_Cerrado_GEE","Zone_EVI", "anisoEVI_eastern.tif"))
kndvi_mask_eastern<- rast(here("Data", "Indices", "kNDVI_Cerrado_GEE","Zone_kndvi", "kndvi_eastern.tif"))
ndvi_mask_eastern<- rast(here("Data", "Indices", "Cerrado_monthlyNDVI_GEE","Zone_ndvi", "ndvi_eastern.tif"))

calc_df<- tibble(index= rep(c("anisoEVI", "kNDVI", "NDVI"), time=3))
calc_df<- calc_df %>% mutate(zone= rep(c("central", "southern", "eastern"), each=3))
list_rasters<- list(evi_mask_central, kndvi_mask_central, ndvi_mask_central,
                    evi_mask_southern, kndvi_mask_southern, ndvi_mask_southern,
                    evi_mask_eastern, kndvi_mask_eastern, ndvi_mask_eastern)

calc_df<- calc_df %>% mutate(raster_stack= list_rasters)
remove(list_rasters)

#1. mean index value of all pixels through time
mean_raster_function<- function (raster_stack){
   mean_of_raster<- terra::global(raster_stack, fun="mean", na.rm=T)
   mean_of_raster #df
}
Sys.time(); calc_df<- calc_df %>% mutate(mean_zone=purrr::map(raster_stack, mean_raster_function)); Sys.time() #4min


sd_raster_function<- function (raster_stack){
   sd_of_raster<- terra::global(raster_stack, fun="sd", na.rm=T)
   sd_of_raster #df
}
Sys.time(); calc_df<- calc_df %>% mutate(sd_zone=purrr::map(raster_stack, sd_raster_function)); Sys.time() #4min

add_timestamp<- function (df){
  x<- tibble(year= rep(2000:2021, each=12))
  x<- x %>% mutate(month= rep(seq(from=1, to=12),times=22))
  x<- x %>% filter(year!=2000 | (month!=1 & month!=2))
  df<- cbind(df,x)
}
Sys.time(); calc_df<- calc_df %>% mutate(mean_zone_timestamp=purrr::map(mean_zone, add_timestamp)); Sys.time() #4min

mean_df<- calc_df %>% dplyr::select(-c(raster_stack, mean_zone)) %>% unnest(c(mean_zone_timestamp, sd_zone))
mean_df<- mean_df %>% mutate(Time= paste0(year, "_", month, "_01"))
mean_df<- mean_df %>% mutate(Time= as_date(Time))
mean_df<- mean_df %>% mutate(lower_ci= mean-sd, upper_ci=mean+sd)

p<- ggplot(data=mean_df, aes(x=Time, y=mean, group=index)) +
  geom_line(aes(color= index))+ 
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci, fill= index), linetype=2, alpha=0.1)+
  ylab("mean value of index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  facet_grid(zone~.)
p<- p+scale_color_brewer( palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2")+
  theme_classic()
ggsave(here("Data", "Indices", "mean_indices_throughtime_zone.png"),p, 
       dpi=700, height = 25, width = 25, units = "cm")

#2. seasonal mean index value through time and zones
seasonal_df<- mean_df %>% group_by(month, index, zone) %>% summarise(mean_of_mean= mean(mean),
                                                                     mean_of_lowerci= mean(lower_ci),
                                                                     mean_of_upperci= mean(upper_ci))

q<- ggplot(data=seasonal_df, aes(x=month, y=mean_of_mean, group=index)) +
  geom_line(aes(color= index))+ 
  geom_ribbon(aes(ymin=mean_of_lowerci, ymax=mean_of_upperci, fill= index), linetype=2, alpha=0.1)+
  ylab("mean value of index") + xlab("Month")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  facet_grid(zone~.)
q<- q+scale_color_brewer( palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2")+
  theme_classic()
ggsave(here("Data", "Indices", "seasonal_mean_indices_throughmonths_zone.png"),q, 
       dpi=700, height = 25, width = 25, units = "cm")


#3. Correlogram of mean index value (through time) seperately for each region
#Central
central_df<- mean_df %>% filter(zone=="central") %>% 
  dplyr::select(c(index, Time, year,mean)) %>%
  group_by(year, index) %>% summarise(annual_mean=mean(mean)) 
pivot_central_df<- pivot_wider(central_df,
                               names_from = index, values_from = annual_mean) %>%
  ungroup %>% dplyr::select(-year)

#install.packages("corrplot")
library(corrplot)
M1<-cor(pivot_central_df)

#pvalue of correlations from 
#http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
p.mat1 <- cor.mtest(pivot_central_df)
png(height=480, width=480, file= here("Data", "Indices", "central_correlogram.png"))
corrplot(
  M1, order = "hclust", type="upper",p.mat=p.mat1, sig.level = 0.01
)
dev.off()

#Southern
southern_df<- mean_df %>% filter(zone=="southern") %>% 
  dplyr::select(c(index, Time, year,mean)) %>%
  group_by(year, index) %>% summarise(annual_mean=mean(mean)) 
pivot_southern_df<- pivot_wider(southern_df,
                               names_from = index, values_from = annual_mean) %>%
  ungroup %>% dplyr::select(-year)

M2<-cor(pivot_southern_df)
p.mat2 <- cor.mtest(pivot_southern_df)

png(height=480, width=480, file= here("Data", "Indices", "southern_correlogram.png"))
corrplot(
  M2, order = "hclust", type="upper",p.mat=p.mat2, sig.level = 0.01
  )
dev.off()

#Eastern
eastern_df<- mean_df %>% filter(zone=="eastern") %>% 
  dplyr::select(c(index, Time, year,mean)) %>%
  group_by(year, index) %>% summarise(annual_mean=mean(mean)) 
pivot_eastern_df<- pivot_wider(eastern_df,
                               names_from = index, values_from = annual_mean) %>%
  ungroup %>% dplyr::select(-year)
M3<-cor(pivot_eastern_df)

p.mat3 <- cor.mtest(pivot_eastern_df)
png(height=480, width=480, file= here("Data", "Indices", "eastern_correlogram.png"))
corrplot(
  M3, order = "hclust", type="upper",p.mat=p.mat3, sig.level = 0.01
)
dev.off() 


remove(M1, M2, M3, p.mat1, p.mat2, p.mat3, pivot_central_df, pivot_eastern_df, pivot_southern_df)
remove(cor.mtest)
```
